name: CD Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@master
        with:
          check-name: checks
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # wait-interval: 10
          # running-workflow-name: 'deploy' # HERE

      # - name: Wait for checks
      #   uses: fountainhead/action-wait-for-check@v1.0.0
      #   id: wait-for-checks
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     checkName: checks

      - name: Merge main -> production
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: production
          github_token: ${{ github.token }}
      - name: Merge main -> demo
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: demo
          github_token: ${{ github.token }}
