name: CI
on: push
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 14.x
      - run: yarn test
        env:
          CI: '1'
